name: clinic-stack

x-image:
  &backend_image ghcr.io/phamngoctien2004/phongkham-be/backend:${TAG:-latest}
# Bạn có thể đổi TAG qua env TAG=sha-xxxx hoặc TAG=main

services:
  backend:
    image: *backend_image
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/auth/test" ]
      interval: 15s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    restart: always
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  mysql_data: { }
  redis-data:
